spacetelescope/pysynphot

- README.rst
> Change RTD domain name

- .gitignore
- MANIFEST.in
- setup.py
Added `relic` as submodule. Clean up setup. This is a follow-up of #1.
> Added relic as submodule

- pysynphot/spectrum.py
Attempt to address #8. Merging now so I can check regression tests on dev.
> Fix GetWaveSet()

- pysynphot/spectrum.py
> Fixed Box spectral element

- pysynphot/observation.py
- pysynphot/spectrum.py
> Fixed bugs based on regtest

- pysynphot/spectrum.py
Fix overlap check for Box now that it is considered an analytic spectrum
> Fix overlap check for Box

- commissioning/basecase.py
- commissioning/doscalars.py
- commissioning/extrap/extrap.py
This PR addresses issue #27 @pllim @stsci-hack Please review this PR.
> Fix for removed 'new_table'

- doc/source/index.rst
Fix #24 
@rjavila , is this how you envision it to be documented?
> Added link to ASCL bibcode

- pysynphot/obsbandpass.py
- pysynphot/refs.py
- pysynphot/test/test_ticket150.py
Fix errors due to deprecation turning to exceptions in Numpy 1.12
> Fix Numpy 1.12 errors

- commissioning/doscalars.py
- pysynphot/compat.py
Fix #40. Should not affect user-facing code.
> Astropy 2.0 compatibility

- pysynphot/observation.py
- pysynphot/test/test_observation.py
Fix #43 where "leak" computation encountered un-physical negative value.
> Fix negative leak

- pysynphot/spectrum.py
- pysynphot/test/test_interp_band.py
> Fix isAnalytic attribute for InterpolatedSpectralElement

- .travis.yml
> Add coverage test on Travis CI

- pysynphot/reddening.py
> Fix misleading Extinction name

- doc/source/index.rst
- pysynphot/reddening.py
Trying out the workflow thingy.
> Prep for 0.9.8.8 release

- doc/source/appendixa.rst
> DOC: Phoenix is stellar models

- doc/source/appendixa.rst
- doc/source/spectrum.rst
- pysynphot/catalog.py
> Correct metallicity definition

- LICENSE.md
- MANIFEST.in
Fix #63 
(Also a good excuse to test to see if new CDBS deliveries broke anything here...)
> Add license from STScI package template

- doc/source/tutorials.rst
- pysynphot/test/test_mergewavesets.py
Fix #81. This is a side effect of fixing #14 via #15 .
> Fix redshift tutorial

- MANIFEST.in
Address #83 for the *next* release.
> Fix missing relic in pip install

- pysynphot/spectrum.py
This arose from a help call (INC0060889).
xref spacetelescope/synphot_refactor#149
> DOC: Clarify integrated unit

- doc/source/appendixa.rst
- doc/source/how_works.rst
- doc/source/index.rst
- pysynphot/test/test_write.py
> Fix outdated FTP doc 

- pysynphot/test/test_spectral_element.py
https://github.com/spacetelescope/pysynphot/pull/113#issuecomment-501525812
> TST: Update new SBC ref

- doc/source/appendixa.rst
- doc/source/appendixb.rst
- doc/source/bandpass.rst
- doc/source/observation.rst
- doc/source/properties.rst
- doc/source/refdata.rst
- doc/source/spectrum.rst
- doc/source/tutorials.rst
- doc/source/units.rst
- doc/tsrs/bandpar_comparison/build/latex/sphinx.sty
- pysynphot/catalog.py
- pysynphot/extinction.py
- pysynphot/planck.py
- pysynphot/reddening.py
- pysynphot/refs.py
- pysynphot/spectrum.py
- pysynphot/units.py
- pysynphot/wavetable.py
> Changed "\textnormal" to "\mathrm" to fix Sphinx math rendering.

- .travis.yml
- pysynphot/test/test_spectral_element.py
- pysynphot/test/test_ticket157.py
- pysynphot/test/test_ticket183.py
- setup.cfg
> Update Travis matrix

- doc/source/appendixa.rst
- doc/source/index.rst
Fix #124 
xref spacetelescope/stsynphot_refactor#100
> Add Brown Atlas to Appendix A

- ROADMAP.md
This might be controversial but decision is necessary, better sooner than later. Open to discussions.
cc @larrybradley @vglaidler
> DOC: Retirement roadmap

- doc/source/appendixa.rst
- doc/source/bandpass.rst
- doc/source/how_works.rst
- doc/source/index.rst
- doc/source/refdata.rst
- doc/source/tutorials.rst
- pysynphot/locations.py
- pysynphot/tables.py
Address code changes for #131
Companion to spacetelescope/synphot_refactor#278 and spacetelescope/stsynphot_refactor#121
> Change CDBS to TRDS

- pysynphot/test/test_locations.py
- pysynphot/test/test_ticket157.py
As a result of astropy/astropy#11006 , similar to spacetelescope/stsynphot_refactor#128
> MNT: Compat with astropy 4.3

- README.rst
Update with end of life notification text.
> Update README.rst with eol text
